### PR TITLE
Make it optional whether the settings page requires authentication

### PR DESCRIPTION
**Pull request by Lenbok**
I'm not too worried about requiring authentication to the settings page, this patch adds a #define that lets you disable the settings page authentication.

### CODE REVIEW

**Comment by Lenbok** [comment]
BTW, I should mention that when I tried using your code with the authentication enabled, I could not actually access the settings page - there was no feedback whether the username/password was correct or incorrect, things just hung.  Maybe there is some a bug in the way authentication is implemented, or maybe in the ESP/arduino library, but I wanted to just get it going, which is why I made it optional via the #define

**Comment by Hopperpop** [comment]
The problem is that this device isn't very secure. The AP password is sent from the browser to the webserver (and back) in plain text. If someone connect his device to the internet, it won't take much for a stranger to get his password. The authentication code isn't the best security, but at least it adds a bit of protection.
If you just connect the device to your local network, it's not really needed. But removing it doesn't solve the security problem. So I want rather improve the security, instead of deleting it (or making it optional).  You're still free to remove it in your own copy.

Normally if you enter a incorrect username/password, the authentication screen reappears. I haven't had many problems with it. The only minor problem is when you press cancel, you get a white screen and need to go back/refresh the page. 

What browser are you using and what version of the program? Do you use the old master branch or the AsyncTcp/ new master branch? (I merged them today)

**Comment by Lenbok** [comment]
Yes, mine is just connected to my local network. I agree that having the authentication working would be a better solution. I did not see any authentication screen after putting the username/password. I was using the old master and I think the browser was either safari or chromium 49.

I have built a second unit, so I will try the current master on it.

**Comment by Lenbok** [comment]
Seems to working fine with the current master on safari. New version looks great. Maybe also plot a point on the map corresponding to the coordinates that the user has entered as their site-coordinates (that way they can check they didn't make a typo with the sign etc?)

**Comment by Hopperpop** [comment]
If you don't have any issues anymore with the authentication, I will close this merge.
I'm going to look into your suggestion today.

**Comment by Lenbok** [comment]
Sounds good.

**Pull request closed without merging**
